#!/applications/R/R-3.4.0/bin/Rscript

# Author: Andrew Tock (ajt200@cam.ac.uk)
# Description: Perform differential expression analysis using read counts generated by Salmon
# Software: R version 3.4.0
#  DESeq2 version 1.16.1

# Note that this R version or later is required for DESeq2 version 1.16 or later,
# in which "the log2 fold change shrinkage is no longer default for the DESeq and nbinomWaldTest functions".
# DESeq2 version 1.16 introduces "a separate function lfcShrink, which performs log2 fold change shrinkage
# for visualization and ranking of genes." (see https://support.bioconductor.org/p/95695/ and
# https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#changes)

# Usage:
# ./DESeq2_differential_expression.R 0.01

args <- commandArgs(trailingOnly = T)
FDRnum <- as.numeric(args[1])
FDRchar <- as.character(args[1])

library(DESeq2)
print(packageVersion("DESeq2"))

inDir <- "/home/ajt200/analysis/170918_Chris_RNAseq_Col_kss/fastq_pooled/DESeq2_TEs_analysis_01/"
outDir <- paste0(inDir, "FDR", FDRchar, "/")
plotDir <- paste0(outDir, "plots/")
system(paste0("[ -d ", outDir, " ] || mkdir ", outDir))
system(paste0("[ -d ", plotDir, " ] || mkdir ", plotDir))

# Load TE-level counts as R list object named "txi"
load(paste0(inDir, "tximport.RData"))

sampleTable <- data.frame(sample = c("wt RNA-seq Rep1", "wt RNA-seq Rep2",
                                     "kss RNA-seq Rep1", "kss RNA-seq Rep2"),
                          condition = factor(rep.int(c("wt", "kss"),
                                                     times = c(2, 2))))
rownames(sampleTable) <- colnames(txi$counts)
print(sampleTable)
#                  sample condition
#sample1  wt RNA-seq Rep1        wt
#sample2  wt RNA-seq Rep2        wt
#sample3 kss RNA-seq Rep1       kss
#sample4 kss RNA-seq Rep2       kss


## Differential expression analysis

# Re-import DESeqDataSet to redefine "dds"
dds <- DESeqDataSetFromTximport(txi = txi,
                                colData = sampleTable,
                                design = ~condition)

# Pre-filter the datasets
print(nrow(dds))
#[1] 30695
# Retain only rows that have more than a single count across all samples
dds <- dds[rowSums(counts(dds)) > 1,]
print(nrow(dds))
#[1] 26416

# Contrast: kss vs wt
dds_kssVwt <- DESeq(dds)
res_kssVwt <- results(dds_kssVwt,
                      contrast = c("condition", "kss", "wt"),
                      alpha = FDRnum)
print(mcols(res_kssVwt, use.names = T))
#DataFrame with 6 rows and 2 columns
#                       type                                 description
#                <character>                                 <character>
#baseMean       intermediate   mean of normalized counts for all samples
#log2FoldChange      results log2 fold change (MLE): condition kss vs wt
#lfcSE               results         standard error: condition kss vs wt
#stat                results         Wald statistic: condition kss vs wt
#pvalue              results      Wald test p-value: condition kss vs wt
#padj                results                        BH adjusted p-values

print(summary(res_kssVwt))

print(table(res_kssVwt$padj < FDRnum))

print(sum(!is.na(res_kssVwt$padj)))

####
# MA-plots
# These show the log2 fold changes in gene expression values for a variable (e.g., treated vs untreated)
# over a the mean of normalized counts for all the samples in the DESeqDataSet

# DESeq2 provides for use of a "Bayesian procedure to moderate (or "shrink") log2 fold changes from genes
# with very low counts and highly variable counts"
# Before generating an MA-plot, the lfcShrink() function should be used to moderate the log2(fold changes) for the contrast
res_kssVwt_lfcShrink <- lfcShrink(dds_kssVwt,
                                  contrast = c("condition", "kss", "wt"),
                                  res = res_kssVwt)
pdf(paste0(plotDir, "MAplot_res_kssVwt_", FDRchar, "_lfcShrink_TEs.pdf"), height = 5, width = 6)
par(mfrow = c(1, 1))
par(mar = c(4.1, 4.1, 2.1, 2.1))
plotMA(res_kssVwt_lfcShrink,
       ylim = c(min(res_kssVwt_lfcShrink$log2FoldChange),
                max(res_kssVwt_lfcShrink$log2FoldChange)),
       xlab = "Mean normalized expression",
       ylab = expression(Log[2]~fold~change),
       colSig = "dodgerblue3",
       colNonSig = "black",
       main = bquote(italic("kyp suvh5 suvh6")*" vs wild type (FDR < "*.(FDRchar)*")"))
#abline(h = c(1, -1), lwd = 1.5, lty = 2, col = "red")
dev.off()


## Exporting results

# Subset results table to significant (padj < FDRnum) down-regulated TEs
res_kssVwt_lfcShrink_Chr <- res_kssVwt_lfcShrink[!grepl("ATM", rownames(res_kssVwt_lfcShrink)) &
                                                 !grepl("ATC", rownames(res_kssVwt_lfcShrink)), ]
res_kssVwt_lfcShrink_Chr_downReg <- res_kssVwt_lfcShrink_Chr[!is.na(res_kssVwt_lfcShrink_Chr$padj) &
                                                             res_kssVwt_lfcShrink_Chr$padj < FDRnum &  
                                                             res_kssVwt_lfcShrink_Chr$log2FoldChange < 0, ]
# OR
#res_kssVwt_lfcShrink_Chr_downReg2 <- subset(res_kssVwt_lfcShrink_Chr, padj < FDRnum & log2FoldChange < 0)

# Sort by increasing log2 fold change estimate
# (TEs with strongest down-regulation)
res_kssVwt_lfcShrink_Chr_downRegSorted <- res_kssVwt_lfcShrink_Chr_downReg[order(res_kssVwt_lfcShrink_Chr_downReg$log2FoldChange), ]
 

# Subset results table to significant (padj < FDRnum) up-regulated TEs
res_kssVwt_lfcShrink_Chr_upReg <- res_kssVwt_lfcShrink_Chr[!is.na(res_kssVwt_lfcShrink_Chr$padj) &
                                                           res_kssVwt_lfcShrink_Chr$padj < FDRnum &  
                                                           res_kssVwt_lfcShrink_Chr$log2FoldChange > 0, ]
# OR
#res_kssVwt_lfcShrink_Chr_upReg2 <- subset(res_kssVwt_lfcShrink_Chr, padj < FDRnum & log2FoldChange > 0)

# Sort by decreasing log2 fold change estimate
# (TEs with strongest up-regulation)
res_kssVwt_lfcShrink_Chr_upRegSorted <- res_kssVwt_lfcShrink_Chr_upReg[order(res_kssVwt_lfcShrink_Chr_upReg$log2FoldChange,
                                                                             decreasing = T), ]

# Convert DataFrame objects (IRanges package) to data.frame objects that can be
# processed by write.table
res_kssVwt_lfcShrink_Chr_downRegSortedDF <- as.data.frame(res_kssVwt_lfcShrink_Chr_downRegSorted)
res_kssVwt_lfcShrink_Chr_upRegSortedDF <- as.data.frame(res_kssVwt_lfcShrink_Chr_upRegSorted)
write.table(res_kssVwt_lfcShrink_Chr_downRegSortedDF,
            file = paste0(outDir, "res_kssVwt_", FDRchar, "_lfcShrink_Chr_downRegSortedDF_TEs.txt"))
write.table(res_kssVwt_lfcShrink_Chr_upRegSortedDF,
            file = paste0(outDir, "res_kssVwt_", FDRchar, "_lfcShrink_Chr_upRegSortedDF_TEs.txt"))

res_kssVwt_lfcShrink_Chr_downRegTEIDs <- rownames(res_kssVwt_lfcShrink_Chr_downRegSortedDF)
res_kssVwt_lfcShrink_Chr_upRegTEIDs <- rownames(res_kssVwt_lfcShrink_Chr_upRegSortedDF)
write.table(res_kssVwt_lfcShrink_Chr_downRegTEIDs,
            file = paste0(outDir, "res_kssVwt_", FDRchar, "_lfcShrink_Chr_downRegTEIDs.txt"))
write.table(res_kssVwt_lfcShrink_Chr_upRegTEIDs,
            file = paste0(outDir, "res_kssVwt_", FDRchar, "_lfcShrink_Chr_upRegTEIDs.txt"))


## Generate plots of log-transformed normalized counts at differentially expressed TEs

downReg_plotDir <- paste0(plotDir, "downReg_counts/")
upReg_plotDir <- paste0(plotDir, "upReg_counts/")
system(paste0("[ -d ", downReg_plotDir, " ] || mkdir ", downReg_plotDir))
system(paste0("[ -d ", upReg_plotDir, " ] || mkdir ", upReg_plotDir))

library(ggplot2)
library(ggbeeswarm)
library(parallel)

dds <- DESeqDataSetFromTximport(txi = txi,
                                colData = sampleTable,
                                design = ~condition)

res_kssVwt_lfcShrink_Chr_downRegTEIDs <- as.character(read.table(file = paste0(outDir,
                                                                               "res_kssVwt_", FDRchar, "_lfcShrink_Chr_downRegTEIDs.txt"))$x)
res_kssVwt_lfcShrink_Chr_upRegTEIDs <- as.character(read.table(file = paste0(outDir,
                                                                             "res_kssVwt_", FDRchar, "_lfcShrink_Chr_upRegTEIDs.txt"))$x)

# Count-plotting function
countPlotFun <- function(geneID, contrast, plotDir) {
  geneCounts <- plotCounts(dds,
                           gene = geneID,
                           intgroup = c("condition", "sample"),
                           normalized = T,
                           transform = T,
                           returnData = T)
  geneCounts$condition <- factor(geneCounts$condition, levels = c("wt", "kss"))
  geneCountsPlot <- ggplot(geneCounts,
                           aes(x = condition,
                               y = count,
                               colour = sample)) +
                    scale_y_log10(breaks = pretty(geneCounts$count)) +
                    geom_beeswarm(cex = 3) +
                    xlab("Genotype") +
                    ylab("Log-transformed normalized count") +
                    labs(colour = "Sample") +
                    theme(plot.margin = grid::unit(c(0,0,0,0), "mm")) +
                    theme_classic() +
                    theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
                    ggtitle(geneID) +
                    theme(plot.title = element_text(hjust = 0.5))
  ggsave(geneCountsPlot,
         file = paste0(plotDir, contrast, "_", geneID, "_normalized_counts.pdf"),
         width = 16, height = 10, units = "cm")
}

mclapply(seq_along(res_kssVwt_lfcShrink_Chr_downRegTEIDs), function(x) {
  countPlotFun(geneID = res_kssVwt_lfcShrink_Chr_downRegTEIDs[x],
               contrast = paste0("kssVwt_", FDRchar, "_lfcShrink_Chr_downReg"),
               plotDir = downReg_plotDir)
}, mc.cores = detectCores())

mclapply(seq_along(res_kssVwt_lfcShrink_Chr_upRegTEIDs), function(x) {
  countPlotFun(geneID = res_kssVwt_lfcShrink_Chr_upRegTEIDs[x],
               contrast = paste0("kssVwt_", FDRchar, "_lfcShrink_Chr_upReg"),
               plotDir = upReg_plotDir)
}, mc.cores = detectCores())


